name = "afu-api"
main = "src/index.mjs"
compatibility_date = "2026-10-06"
account_id = "42e79186125e8ff83e51f15816e074de"
workers_dev = false
routes = [{ pattern = "api.afuchat.com/", zone_name = "afuchat.com" }]

[[services]]
binding = "AFUAUTH_API"
service = "afuauth-api"
environment = "production"

[observability]
enabled = true
