const BRAND = "#00C2CB";
const BRAND_DARK = "#00A8B0";
const BRAND_BLUE = "#1677FF";

export default {
  brand: BRAND,
  brandDark: BRAND_DARK,
  blue: BRAND_BLUE,
  light: {
    text: "#111111",
    textSecondary: "#888888",
    textMuted: "#AAAAAA",
    background: "#FFFFFF",
    backgroundSecondary: "#F7F7F7",
    backgroundTertiary: "#EFEFEF",
    surface: "#FFFFFF",
    border: "#E8E8E8",
    tint: BRAND,
    tabIconDefault: "#AAAAAA",
    tabIconSelected: BRAND,
    bubble: "#00C2CB",
    bubbleText: "#FFFFFF",
    bubbleIncoming: "#F0F0F0",
    bubbleIncomingText: "#111111",
    inputBg: "#F2F2F2",
    header: "#FFFFFF",
    separator: "#F0F0F0",
    badgeBg: "#FF3B30",
    badgeText: "#FFFFFF",
    avatar: "#E0E0E0",
    online: "#00C2CB",
    unread: BRAND,
  },
  dark: {
    text: "#FFFFFF",
    textSecondary: "#999999",
    textMuted: "#666666",
    background: "#1C1C1C",
    backgroundSecondary: "#242424",
    backgroundTertiary: "#2C2C2C",
    surface: "#242424",
    border: "#333333",
    tint: BRAND,
    tabIconDefault: "#666666",
    tabIconSelected: BRAND,
    bubble: "#00C2CB",
    bubbleText: "#FFFFFF",
    bubbleIncoming: "#2C2C2C",
    bubbleIncomingText: "#FFFFFF",
    inputBg: "#2C2C2C",
    header: "#1C1C1C",
    separator: "#2C2C2C",
    badgeBg: "#FF3B30",
    badgeText: "#FFFFFF",
    avatar: "#444444",
    online: "#00C2CB",
    unread: BRAND,
  },
};
