const BRAND = "#00BCD4";
const BRAND_DARK = "#0097A7";
const BRAND_BLUE = "#1677FF";
const GOLD = "#D4A853";

export default {
  brand: BRAND,
  brandDark: BRAND_DARK,
  blue: BRAND_BLUE,
  gold: GOLD,
  light: {
    text: "#1A1A1A",
    textSecondary: "#6B6B6B",
    textMuted: "#9E9E9E",
    background: "#FDF8F3",
    backgroundSecondary: "#F5F0EB",
    backgroundTertiary: "#EDE8E3",
    surface: "#FFFFFF",
    border: "#E8E2DB",
    tint: BRAND,
    tabIconDefault: "#A0A0A0",
    tabIconSelected: BRAND,
    bubble: "#00BCD4",
    bubbleText: "#FFFFFF",
    bubbleIncoming: "#E8E2DB",
    bubbleIncomingText: "#1A1A1A",
    inputBg: "#F0EBE6",
    header: "#FFFFFF",
    separator: "#EDE8E3",
    badgeBg: "#FF3B30",
    badgeText: "#FFFFFF",
    avatar: "#E0DBD6",
    online: "#00BCD4",
    unread: BRAND,
  },
  dark: {
    text: "#F2F2F7",
    textSecondary: "#8E8E93",
    textMuted: "#636366",
    background: "#000000",
    backgroundSecondary: "#0A0A0A",
    backgroundTertiary: "#141414",
    surface: "#1C1C1E",
    border: "#2C2C2E",
    tint: BRAND,
    tabIconDefault: "#636366",
    tabIconSelected: BRAND,
    bubble: "#00BCD4",
    bubbleText: "#FFFFFF",
    bubbleIncoming: "#1C1C1E",
    bubbleIncomingText: "#F2F2F7",
    inputBg: "#1C1C1E",
    header: "#000000",
    separator: "#2C2C2E",
    badgeBg: "#FF3B30",
    badgeText: "#FFFFFF",
    avatar: "#2C2C2E",
    online: "#00BCD4",
    unread: BRAND,
  },
};
