export type Country = {
  name: string;
  code: string;
  dial: string;
  flag: string;
  phoneLength: number[];
};

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AF", dial: "+93", flag: "🇦🇫", phoneLength: [9] },
  { name: "Albania", code: "AL", dial: "+355", flag: "🇦🇱", phoneLength: [9] },
  { name: "Algeria", code: "DZ", dial: "+213", flag: "🇩🇿", phoneLength: [9] },
  { name: "Angola", code: "AO", dial: "+244", flag: "🇦🇴", phoneLength: [9] },
  { name: "Argentina", code: "AR", dial: "+54", flag: "🇦🇷", phoneLength: [10, 11] },
  { name: "Australia", code: "AU", dial: "+61", flag: "🇦🇺", phoneLength: [9] },
  { name: "Austria", code: "AT", dial: "+43", flag: "🇦🇹", phoneLength: [10, 11] },
  { name: "Bangladesh", code: "BD", dial: "+880", flag: "🇧🇩", phoneLength: [10] },
  { name: "Belgium", code: "BE", dial: "+32", flag: "🇧🇪", phoneLength: [9, 10] },
  { name: "Benin", code: "BJ", dial: "+229", flag: "🇧🇯", phoneLength: [8] },
  { name: "Bolivia", code: "BO", dial: "+591", flag: "🇧🇴", phoneLength: [8] },
  { name: "Botswana", code: "BW", dial: "+267", flag: "🇧🇼", phoneLength: [7, 8] },
  { name: "Brazil", code: "BR", dial: "+55", flag: "🇧🇷", phoneLength: [10, 11] },
  { name: "Burkina Faso", code: "BF", dial: "+226", flag: "🇧🇫", phoneLength: [8] },
  { name: "Burundi", code: "BI", dial: "+257", flag: "🇧🇮", phoneLength: [8] },
  { name: "Cambodia", code: "KH", dial: "+855", flag: "🇰🇭", phoneLength: [8, 9] },
  { name: "Cameroon", code: "CM", dial: "+237", flag: "🇨🇲", phoneLength: [9] },
  { name: "Canada", code: "CA", dial: "+1", flag: "🇨🇦", phoneLength: [10] },
  { name: "Central African Republic", code: "CF", dial: "+236", flag: "🇨🇫", phoneLength: [8] },
  { name: "Chad", code: "TD", dial: "+235", flag: "🇹🇩", phoneLength: [8] },
  { name: "Chile", code: "CL", dial: "+56", flag: "🇨🇱", phoneLength: [9] },
  { name: "China", code: "CN", dial: "+86", flag: "🇨🇳", phoneLength: [11] },
  { name: "Colombia", code: "CO", dial: "+57", flag: "🇨🇴", phoneLength: [10] },
  { name: "Comoros", code: "KM", dial: "+269", flag: "🇰🇲", phoneLength: [7] },
  { name: "Congo (DRC)", code: "CD", dial: "+243", flag: "🇨🇩", phoneLength: [9] },
  { name: "Congo (Republic)", code: "CG", dial: "+242", flag: "🇨🇬", phoneLength: [9] },
  { name: "Costa Rica", code: "CR", dial: "+506", flag: "🇨🇷", phoneLength: [8] },
  { name: "Cote d'Ivoire", code: "CI", dial: "+225", flag: "🇨🇮", phoneLength: [10] },
  { name: "Croatia", code: "HR", dial: "+385", flag: "🇭🇷", phoneLength: [8, 9] },
  { name: "Cuba", code: "CU", dial: "+53", flag: "🇨🇺", phoneLength: [8] },
  { name: "Czech Republic", code: "CZ", dial: "+420", flag: "🇨🇿", phoneLength: [9] },
  { name: "Denmark", code: "DK", dial: "+45", flag: "🇩🇰", phoneLength: [8] },
  { name: "Djibouti", code: "DJ", dial: "+253", flag: "🇩🇯", phoneLength: [8] },
  { name: "Dominican Republic", code: "DO", dial: "+1", flag: "🇩🇴", phoneLength: [10] },
  { name: "Ecuador", code: "EC", dial: "+593", flag: "🇪🇨", phoneLength: [9] },
  { name: "Egypt", code: "EG", dial: "+20", flag: "🇪🇬", phoneLength: [10] },
  { name: "El Salvador", code: "SV", dial: "+503", flag: "🇸🇻", phoneLength: [8] },
  { name: "Equatorial Guinea", code: "GQ", dial: "+240", flag: "🇬🇶", phoneLength: [9] },
  { name: "Eritrea", code: "ER", dial: "+291", flag: "🇪🇷", phoneLength: [7] },
  { name: "Estonia", code: "EE", dial: "+372", flag: "🇪🇪", phoneLength: [7, 8] },
  { name: "Eswatini", code: "SZ", dial: "+268", flag: "🇸🇿", phoneLength: [8] },
  { name: "Ethiopia", code: "ET", dial: "+251", flag: "🇪🇹", phoneLength: [9] },
  { name: "Finland", code: "FI", dial: "+358", flag: "🇫🇮", phoneLength: [9, 10] },
  { name: "France", code: "FR", dial: "+33", flag: "🇫🇷", phoneLength: [9] },
  { name: "Gabon", code: "GA", dial: "+241", flag: "🇬🇦", phoneLength: [7, 8] },
  { name: "Gambia", code: "GM", dial: "+220", flag: "🇬🇲", phoneLength: [7] },
  { name: "Georgia", code: "GE", dial: "+995", flag: "🇬🇪", phoneLength: [9] },
  { name: "Germany", code: "DE", dial: "+49", flag: "🇩🇪", phoneLength: [10, 11] },
  { name: "Ghana", code: "GH", dial: "+233", flag: "🇬🇭", phoneLength: [9] },
  { name: "Greece", code: "GR", dial: "+30", flag: "🇬🇷", phoneLength: [10] },
  { name: "Guatemala", code: "GT", dial: "+502", flag: "🇬🇹", phoneLength: [8] },
  { name: "Guinea", code: "GN", dial: "+224", flag: "🇬🇳", phoneLength: [9] },
  { name: "Guinea-Bissau", code: "GW", dial: "+245", flag: "🇬🇼", phoneLength: [7] },
  { name: "Haiti", code: "HT", dial: "+509", flag: "🇭🇹", phoneLength: [8] },
  { name: "Honduras", code: "HN", dial: "+504", flag: "🇭🇳", phoneLength: [8] },
  { name: "Hungary", code: "HU", dial: "+36", flag: "🇭🇺", phoneLength: [9] },
  { name: "India", code: "IN", dial: "+91", flag: "🇮🇳", phoneLength: [10] },
  { name: "Indonesia", code: "ID", dial: "+62", flag: "🇮🇩", phoneLength: [10, 11, 12] },
  { name: "Iran", code: "IR", dial: "+98", flag: "🇮🇷", phoneLength: [10] },
  { name: "Iraq", code: "IQ", dial: "+964", flag: "🇮🇶", phoneLength: [10] },
  { name: "Ireland", code: "IE", dial: "+353", flag: "🇮🇪", phoneLength: [9] },
  { name: "Israel", code: "IL", dial: "+972", flag: "🇮🇱", phoneLength: [9] },
  { name: "Italy", code: "IT", dial: "+39", flag: "🇮🇹", phoneLength: [10] },
  { name: "Jamaica", code: "JM", dial: "+1", flag: "🇯🇲", phoneLength: [10] },
  { name: "Japan", code: "JP", dial: "+81", flag: "🇯🇵", phoneLength: [10] },
  { name: "Jordan", code: "JO", dial: "+962", flag: "🇯🇴", phoneLength: [9] },
  { name: "Kazakhstan", code: "KZ", dial: "+7", flag: "🇰🇿", phoneLength: [10] },
  { name: "Kenya", code: "KE", dial: "+254", flag: "🇰🇪", phoneLength: [9] },
  { name: "Kuwait", code: "KW", dial: "+965", flag: "🇰🇼", phoneLength: [8] },
  { name: "Lebanon", code: "LB", dial: "+961", flag: "🇱🇧", phoneLength: [7, 8] },
  { name: "Lesotho", code: "LS", dial: "+266", flag: "🇱🇸", phoneLength: [8] },
  { name: "Liberia", code: "LR", dial: "+231", flag: "🇱🇷", phoneLength: [7, 8] },
  { name: "Libya", code: "LY", dial: "+218", flag: "🇱🇾", phoneLength: [9] },
  { name: "Madagascar", code: "MG", dial: "+261", flag: "🇲🇬", phoneLength: [9] },
  { name: "Malawi", code: "MW", dial: "+265", flag: "🇲🇼", phoneLength: [9] },
  { name: "Malaysia", code: "MY", dial: "+60", flag: "🇲🇾", phoneLength: [9, 10] },
  { name: "Mali", code: "ML", dial: "+223", flag: "🇲🇱", phoneLength: [8] },
  { name: "Mauritania", code: "MR", dial: "+222", flag: "🇲🇷", phoneLength: [8] },
  { name: "Mauritius", code: "MU", dial: "+230", flag: "🇲🇺", phoneLength: [8] },
  { name: "Mexico", code: "MX", dial: "+52", flag: "🇲🇽", phoneLength: [10] },
  { name: "Morocco", code: "MA", dial: "+212", flag: "🇲🇦", phoneLength: [9] },
  { name: "Mozambique", code: "MZ", dial: "+258", flag: "🇲🇿", phoneLength: [9] },
  { name: "Myanmar", code: "MM", dial: "+95", flag: "🇲🇲", phoneLength: [8, 9, 10] },
  { name: "Namibia", code: "NA", dial: "+264", flag: "🇳🇦", phoneLength: [9] },
  { name: "Nepal", code: "NP", dial: "+977", flag: "🇳🇵", phoneLength: [10] },
  { name: "Netherlands", code: "NL", dial: "+31", flag: "🇳🇱", phoneLength: [9] },
  { name: "New Zealand", code: "NZ", dial: "+64", flag: "🇳🇿", phoneLength: [8, 9] },
  { name: "Nicaragua", code: "NI", dial: "+505", flag: "🇳🇮", phoneLength: [8] },
  { name: "Niger", code: "NE", dial: "+227", flag: "🇳🇪", phoneLength: [8] },
  { name: "Nigeria", code: "NG", dial: "+234", flag: "🇳🇬", phoneLength: [10] },
  { name: "Norway", code: "NO", dial: "+47", flag: "🇳🇴", phoneLength: [8] },
  { name: "Oman", code: "OM", dial: "+968", flag: "🇴🇲", phoneLength: [8] },
  { name: "Pakistan", code: "PK", dial: "+92", flag: "🇵🇰", phoneLength: [10] },
  { name: "Panama", code: "PA", dial: "+507", flag: "🇵🇦", phoneLength: [7, 8] },
  { name: "Paraguay", code: "PY", dial: "+595", flag: "🇵🇾", phoneLength: [9] },
  { name: "Peru", code: "PE", dial: "+51", flag: "🇵🇪", phoneLength: [9] },
  { name: "Philippines", code: "PH", dial: "+63", flag: "🇵🇭", phoneLength: [10] },
  { name: "Poland", code: "PL", dial: "+48", flag: "🇵🇱", phoneLength: [9] },
  { name: "Portugal", code: "PT", dial: "+351", flag: "🇵🇹", phoneLength: [9] },
  { name: "Qatar", code: "QA", dial: "+974", flag: "🇶🇦", phoneLength: [8] },
  { name: "Romania", code: "RO", dial: "+40", flag: "🇷🇴", phoneLength: [9] },
  { name: "Russia", code: "RU", dial: "+7", flag: "🇷🇺", phoneLength: [10] },
  { name: "Rwanda", code: "RW", dial: "+250", flag: "🇷🇼", phoneLength: [9] },
  { name: "Saudi Arabia", code: "SA", dial: "+966", flag: "🇸🇦", phoneLength: [9] },
  { name: "Senegal", code: "SN", dial: "+221", flag: "🇸🇳", phoneLength: [9] },
  { name: "Serbia", code: "RS", dial: "+381", flag: "🇷🇸", phoneLength: [8, 9] },
  { name: "Sierra Leone", code: "SL", dial: "+232", flag: "🇸🇱", phoneLength: [8] },
  { name: "Singapore", code: "SG", dial: "+65", flag: "🇸🇬", phoneLength: [8] },
  { name: "Slovakia", code: "SK", dial: "+421", flag: "🇸🇰", phoneLength: [9] },
  { name: "Somalia", code: "SO", dial: "+252", flag: "🇸🇴", phoneLength: [7, 8] },
  { name: "South Africa", code: "ZA", dial: "+27", flag: "🇿🇦", phoneLength: [9] },
  { name: "South Korea", code: "KR", dial: "+82", flag: "🇰🇷", phoneLength: [10, 11] },
  { name: "South Sudan", code: "SS", dial: "+211", flag: "🇸🇸", phoneLength: [9] },
  { name: "Spain", code: "ES", dial: "+34", flag: "🇪🇸", phoneLength: [9] },
  { name: "Sri Lanka", code: "LK", dial: "+94", flag: "🇱🇰", phoneLength: [9] },
  { name: "Sudan", code: "SD", dial: "+249", flag: "🇸🇩", phoneLength: [9] },
  { name: "Sweden", code: "SE", dial: "+46", flag: "🇸🇪", phoneLength: [9] },
  { name: "Switzerland", code: "CH", dial: "+41", flag: "🇨🇭", phoneLength: [9] },
  { name: "Syria", code: "SY", dial: "+963", flag: "🇸🇾", phoneLength: [9] },
  { name: "Taiwan", code: "TW", dial: "+886", flag: "🇹🇼", phoneLength: [9] },
  { name: "Tanzania", code: "TZ", dial: "+255", flag: "🇹🇿", phoneLength: [9] },
  { name: "Thailand", code: "TH", dial: "+66", flag: "🇹🇭", phoneLength: [9] },
  { name: "Togo", code: "TG", dial: "+228", flag: "🇹🇬", phoneLength: [8] },
  { name: "Trinidad and Tobago", code: "TT", dial: "+1", flag: "🇹🇹", phoneLength: [10] },
  { name: "Tunisia", code: "TN", dial: "+216", flag: "🇹🇳", phoneLength: [8] },
  { name: "Turkey", code: "TR", dial: "+90", flag: "🇹🇷", phoneLength: [10] },
  { name: "Uganda", code: "UG", dial: "+256", flag: "🇺🇬", phoneLength: [9] },
  { name: "Ukraine", code: "UA", dial: "+380", flag: "🇺🇦", phoneLength: [9] },
  { name: "United Arab Emirates", code: "AE", dial: "+971", flag: "🇦🇪", phoneLength: [9] },
  { name: "United Kingdom", code: "GB", dial: "+44", flag: "🇬🇧", phoneLength: [10] },
  { name: "United States", code: "US", dial: "+1", flag: "🇺🇸", phoneLength: [10] },
  { name: "Uruguay", code: "UY", dial: "+598", flag: "🇺🇾", phoneLength: [8] },
  { name: "Uzbekistan", code: "UZ", dial: "+998", flag: "🇺🇿", phoneLength: [9] },
  { name: "Venezuela", code: "VE", dial: "+58", flag: "🇻🇪", phoneLength: [10] },
  { name: "Vietnam", code: "VN", dial: "+84", flag: "🇻🇳", phoneLength: [9, 10] },
  { name: "Yemen", code: "YE", dial: "+967", flag: "🇾🇪", phoneLength: [9] },
  { name: "Zambia", code: "ZM", dial: "+260", flag: "🇿🇲", phoneLength: [9] },
  { name: "Zimbabwe", code: "ZW", dial: "+263", flag: "🇿🇼", phoneLength: [9] },
];
