/**
 * PostgREST routing for resources used by AfuChat.
 *
 * AfuChat-owned resources stay in afuchat. The small set of external resources
 * below are explicit targets used by the application contract; unknown names
 * are never retried against another schema.
 */
const AFUCHAT_RELATIONS = [
  "acoin_transactions",
  "achievements",
  "activity_rewards",
  "ad_campaigns",
  "ad_clicks",
  "ad_impressions",
  "advanced_feature_settings",
  "affiliate_requests",
  "afuchat_donations",
  "afumail_aliases",
  "afumail_emails",
  "afumail_mailboxes",
  "afumail_recipients",
  "afumail_user_emails",
  "ai_conversations",
  "ai_memories",
  "ai_messages",
  "app_settings",
  "blocked_users",
  "blog_articles",
  "calls",
  "channel_subscriptions",
  "channels",
  "chat_drafts",
  "chat_folder_assignments",
  "chat_folders",
  "chat_label_assignments",
  "chat_labels",
  "chat_media",
  "chat_members",
  "chat_messages",
  "chat_mutes",
  "chat_preferences",
  "chat_themes",
  "chat_wallpapers",
  "chats",
  "collection_items",
  "collections",
  "community_members",
  "conversation_participants",
  "conversations",
  "crash_logs",
  "creator_earnings",
  "creator_monetize_settings",
  "creator_withdrawals",
  "currency_settings",
  "developer_applications",
  "developer_roles",
  "developer_showcase",
  "device_sessions",
  "digital_events",
  "engagera_admins",
  "engagera_api_keys",
  "engagera_api_logs",
  "engagera_conversations",
  "engagera_dataset_candidates",
  "engagera_dataset_versions",
  "engagera_document_chunks",
  "engagera_documents",
  "engagera_guest_sessions",
  "engagera_knowledge_base",
  "engagera_memories",
  "engagera_messages",
  "engagera_model_registry",
  "engagera_request_logs",
  "engagera_reviewer_logs",
  "engagera_training_jobs",
  "engagera_usage_records",
  "engagera_user_memory",
  "engagera_user_settings",
  "freelance_listings",
  "freelance_orders",
  "freelance_reviews",
  "follow_requests",
  "follows",
  "gift_marketplace",
  "gift_statistics",
  "gift_transactions",
  "gifts",
  "life_earth_saves",
  "match_matches",
  "match_messages",
  "match_photos",
  "match_preferences",
  "match_profiles",
  "match_reports",
  "match_swipes",
  "messages",
  "message_edit_history",
  "message_reports",
  "message_status",
  "money_requests",
  "music_purchases",
  "music_tracks",
  "notification_events",
  "org_verification_requests",
  "organization_page_connections",
  "organization_page_followers",
  "organization_page_posts",
  "organization_pages",
  "owned_usernames",
  "paid_communities",
  "post_acknowledgments",
  "post_bookmarks",
  "post_images",
  "post_reply_likes",
  "post_replies",
  "post_views",
  "posts",
  "red_envelope_claims",
  "red_envelopes",
  "security_preferences",
  "seller_applications",
  "shop_order_items",
  "shop_order_messages",
  "shop_orders",
  "shop_products",
  "shop_reviews",
  "shopping_cart",
  "shops",
  "status_goods_purchases",
  "stories",
  "story_likes",
  "story_replies",
  "story_views",
  "subscription_plans",
  "support_messages",
  "support_tickets",
  "starred_messages",
  "user_activity_events",
  "user_gifts",
  "user_reports",
  "user_subscriptions",
  "username_featured_listings",
  "username_listings",
  "video_watch_history",
  "video_assets",
  "xp_transfers",
] as const;

export const RELATION_SCHEMA_BY_NAME: Readonly<Record<string, string>> = Object.freeze({
  ...Object.fromEntries(AFUCHAT_RELATIONS.map((name) => [name, "afuchat"])),
  // These resources are explicit AfuChat contract references outside afuchat.
  profiles: "accounts",
  orders: "shop",
});

export const RPC_SCHEMA_BY_NAME: Readonly<Record<string, string>> = Object.freeze({
  get_chat_list: "afuchat",
  get_or_create_direct_chat: "afuchat",
});

export function schemaForRelation(name: string): string | null {
  return RELATION_SCHEMA_BY_NAME[name] ?? null;
}

export function schemaForRpc(name: string): string | null {
  return RPC_SCHEMA_BY_NAME[name] ?? null;
}

export function schemaForPostgrestPath(pathname: string): string | null {
  const match = pathname.match(/^\/rest\/v1\/(rpc\/)?([a-z][a-z0-9_]*)$/);
  if (!match) return null;
  return match[1] ? schemaForRpc(match[2]) : schemaForRelation(match[2]);
}
