import type { ModuleManifest } from "./types";

export const SUPER_APP_REGISTRY: ModuleManifest[] = [
  {
    id: "afupay",
    name: "AfuPay",
    description: "Send, receive, top up, and manage your ACoins & Nexa.",
    version: "2.0.0",
    icon: "wallet",
    gradient: ["#34C759", "#00C781"] as const,
    keepAlive: true,
  },
  {
    id: "afumarket",
    name: "AfuMarket",
    description: "Shop from verified stores and sellers.",
    version: "1.0.0",
    icon: "storefront",
    gradient: ["#AF52DE", "#BF5AF2"] as const,
    keepAlive: false,
    badge: "NEW",
  },
  {
    id: "afugames",
    name: "AfuGames",
    description: "Play games and compete with friends.",
    version: "1.0.0",
    icon: "game-controller",
    gradient: ["#FF3B30", "#FF6B35"] as const,
    keepAlive: false,
  },
  {
    id: "afubusiness",
    name: "AfuBusiness",
    description: "Tools and analytics for your business.",
    version: "1.0.0",
    icon: "briefcase",
    gradient: ["#1C1C1E", "#3A3A3C"] as const,
    keepAlive: false,
  },
  {
    id: "afusearch",
    name: "AfuSearch",
    description: "Find people, posts, channels, events and more.",
    version: "1.0.0",
    icon: "search",
    gradient: ["#5856D6", "#6E6CD3"] as const,
    keepAlive: false,
  },
  {
    id: "afufreelance",
    name: "AfuFreelance",
    description: "Hire talent or find work on AfuFreelance.",
    version: "1.0.0",
    icon: "briefcase",
    gradient: ["#34C759", "#30D158"] as const,
    keepAlive: false,
    badge: "NEW",
  },
  {
    id: "afugifts",
    name: "AfuGifts",
    description: "Send animated gifts to people you love.",
    version: "1.0.0",
    icon: "gift",
    gradient: ["#FF3B30", "#FF453A"] as const,
    keepAlive: false,
  },
  {
    id: "afuqr",
    name: "QR Scanner",
    description: "Scan any QR code for links, Wi-Fi, contacts and more.",
    version: "1.0.0",
    icon: "qr-code",
    gradient: ["#1C1C1E", "#3A3A3C"] as const,
    keepAlive: false,
    nativeOnly: true,
  },
  {
    id: "afusaved",
    name: "Saved",
    description: "Saved posts, starred messages, and your collections.",
    version: "1.0.0",
    icon: "bookmark",
    gradient: ["#FF6B35", "#FF8C00"] as const,
    keepAlive: false,
  },
  {
    id: "afumusic",
    name: "Music",
    description: "Discover independent sounds and keep your library offline.",
    version: "1.0.0",
    icon: "musical-notes",
    gradient: ["#19172F", "#F06451"] as const,
    keepAlive: false,
    nativeOnly: true,
    badge: "NEW",
  },
  {
    id: "afucollections",
    name: "Collections",
    description: "Curate and share themed collections.",
    version: "1.0.0",
    icon: "albums",
    gradient: ["#BF5AF2", "#AF52DE"] as const,
    keepAlive: false,
  },
  {
    id: "afumatch",
    name: "AfuMatch",
    description: "Meet new people and find meaningful connections.",
    version: "1.0.0",
    icon: "heart",
    gradient: ["#FF2D55", "#FF375F"] as const,
    keepAlive: false,
  },
  {
    id: "afuevents",
    name: "Events",
    description: "Discover local and online events near you.",
    version: "1.0.0",
    icon: "calendar",
    gradient: ["#FF9500", "#FFCC00"] as const,
    keepAlive: false,
  },
  {
    id: "afuusernames",
    name: "Handle Market",
    description: "Buy and sell premium @handles.",
    version: "1.0.0",
    icon: "at",
    gradient: ["#007AFF", "#5AC8FA"] as const,
    keepAlive: false,
  },
];

export const SUPER_APP_ID_SET = new Set(SUPER_APP_REGISTRY.map((m) => m.id));

export function findModule(id: string): ModuleManifest | undefined {
  return SUPER_APP_REGISTRY.find((m) => m.id === id);
}